"""change the structure schedule

Revision ID: 9a775ce32d4f
Revises: ec8fe69d9e84
Create Date: 2024-07-17 14:46:35.069763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a775ce32d4f'
down_revision = 'ec8fe69d9e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('imageUrl',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('scheduleTitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('scheduleTitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('imageUrl',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
