"""change the structur column on user

Revision ID: ec8fe69d9e84
Revises: 
Create Date: 2024-07-14 18:46:02.353501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8fe69d9e84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('npm', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prodi', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('univ', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('anakke', sa.Integer(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('anakke')
        batch_op.drop_column('univ')
        batch_op.drop_column('prodi')
        batch_op.drop_column('npm')

    # ### end Alembic commands ###
